# Generated by Django 5.2.4 on 2025-08-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlsaver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlentry',
            name='category',
            field=models.CharField(blank=True, default='NotKnown', max_length=100, null=True),
        ),
    ]
