# Generated by Django 5.2.4 on 2025-08-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlsaver', '0002_alter_urlentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlentry',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
