# Generated by Django 5.2.4 on 2025-08-15 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlsaver', '0003_alter_urlentry_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlgroupentry',
            name='group',
        ),
        migrations.AddField(
            model_name='urlentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UrlGroup',
        ),
        migrations.DeleteModel(
            name='UrlGroupEntry',
        ),
    ]
